version: '3.8'

services:
  postgres:
    # Use pgvector-enabled PostgreSQL image
    image: pgvector/pgvector:pg16
    container_name: dd-postgresql
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    networks:
      - job_matching_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G  # Increased for vector operations
    volumes:
      - pgdata:/data/postgres
      # Add initialization script to enable pgvector
      - ./db/init-pgvector.sql:/docker-entrypoint-initdb.d/01-init-pgvector.sql

volumes:
  pgdata:
  pgadmin_data:

networks:
  job_matching_network:
    driver: bridge